config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'home#index'

  resources :cards

end

app/models/card.rb
class Card < ActiveRecord::Base

  before_validation :ensure_review_date_exists

  validates :original_text, :translated_text, :review_date, presence: true

  validate :validate_original_vs_translated

  private
    def validate_original_vs_translated
      if original_text.to_s.downcase == translated_text.to_s.downcase
        errors.add(:original_text, "texts shouldn't match")
      end
    end

  protected
    def ensure_review_date_exists
      if review_date.nil?
        self.review_date = DateTime.now.to_date + 3
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :find_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = Card.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def update
    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy

    redirect_to cards_path
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date)
    end

  def find_card
    @card = Card.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>

  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
    <div class="form-group">
      <div class="col-xs-10">
        <%= f.input :original_text, label: 'Оригинальный', wrapper_html: { class: 'col-sm-2 control-label' } %>
      </div>
      <div class="col-xs-10">
        <%= f.input :translated_text, label: 'Перевод', wrapper_html: { class: 'col-sm-2 control-label' } %>
      </div>
      <div class="col-xs-10">
        <%= f.label :review_date, "Дата пересмотра" %>
        <%= f.date_select :review_date, default: 3.days.from_now, use_month_numbers: true, class: "form-control" %>
      </div>
      <div class="col-xs-10">
        <%= f.button :submit, 'Сохранить', wrapper_html: { class: 'col-sm-2 control-label' } %>
      </div>
    </div>
  </form>
<% end %>

app/views/cards/edit.html.erb
<h1>Редактировать карточку</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="container">
  <h3>Все карточки</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Оригинальный</th>
        <th>Перевод</th>
        <th>Дата пересмотра</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.original_text %></td>
        <td><%= card.translated_text %></td>
        <td><%= card.review_date %></td>
        <td><%= link_to 'Редактировать', edit_card_path(card) %></td>
        <td><%= link_to 'Удалить', card_path(card),
              method: :delete,
              data: { confirm: 'Уеренны, что хотите удалить?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/cards/new.html.erb
<h1>Добавить карточку</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p>
  <strong>Оригинальный</strong>
  <%= @card.original_text %>
</p>
<p>
  <strong>Перевод</strong>
    <%= @card.translated_text %>
</p>
<p>
  <strong>Дата пересмотра</strong>
    <%= @card.review_date %>
</p>

app/views/home/index.html.erb
<div class="page-header center">
  <h1>Первый в мире удобный менеджер флеш-карточек. <small>Именно так.</small></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Флэшкарточкер</title>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="application.css">
    <title>Флэшкарточкер</title>
</head>
<body>
  <section id="container">
    <%= render "shared/header" %>
    <%= yield %>
  </section>
</body>
</html>

app/views/shared/_header.html.erb
<header class='clearfix'>
  <nav role='navigation' class='navbar navbar-default navbar-fixed-top'>
    <div class='container-fluid'>
      <div class='navbar-header'>
        <button type='button' data-target='#navbarCollapse' data-toggle='collapse' class='navbar-toggle'>
          <span class='sr-only'>Toggle</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <div class='navbar-brand'>
          <%= link_to 'Флэшкарточкер', home_path %>
        </div>
      </div>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to 'Все карточки', cards_path %></li>
        <li><%= link_to 'Добавить карточку', new_card_path %></a></li>
      </ul>
    </div>
  </nav>
</header>